pub mod player;
pub mod camera_view;
pub mod platform;
pub mod medium_platform;
pub mod falling_platform;
pub mod coin;
pub mod cloud;
pub mod flag;
pub mod grass_platform;

pub use player::spawn_player;
pub use camera_view::spawn_camera_view;
pub use platform::spawn_platform;
pub use medium_platform::spawn_medium_platform;
pub use falling_platform::spawn_falling_platform;
pub use coin::spawn_coin;
pub use cloud::spawn_cloud;
pub use flag::spawn_flag;
pub use grass_platform::spawn_grass_platform;
